# Numpy

## Numpy & List Benzerlikleri ve Farkları

* Numpy ve List de elemanlara aynı şekilde pozisyon bazlı erişim mevcuttur.
* Numpy ve List de elemanlara aynı şekilde aralıkla erişebiliriz ( np[0:2] ).
* Numpy ve List üzerinde aynı döngü kullanabiliriz (for i in np:)

* Numpy dizilerinde aynı tip eleman bulunur. Listlerde ise farklı tip elemanlarda bulunur.
* Numpy da otomatik foksiyonları kullanabiliriz (mean(), std()) ancak list de kullanamayız.

* Numpy list e göre çok daha hızlıdır.(50 kat 100 kat)


In [13]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

## Why Numpy

In [14]:
# Python list speed 2.2 seconds
import time
def trad_version():
    t1 = time.time()
    X = range(10000000)
    Y = range(10000000)
    Z = []
    for i in range (len (X)):
        Z. append (X[i] + Y[i])
    return time.time() - t1
trad_version()

2.209183931350708

In [15]:
# Numpy Speed 0.05 seconds
def numpy_version():
    t1 = time.time()
    X = np.arange(10000000)
    Y = np.arange(10000000)
    Z = X + Y
    return time.time() - t1
numpy_version()

0.07529902458190918

## list to array
---

In [16]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [17]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [18]:
type(arr1)

numpy.ndarray

---

### Arrayin içindeki verinin tipi (dtype)
---

In [19]:
arr1.dtype

dtype('int64')

---

### Tip değiştirme (astype())
---

In [20]:
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

---

### Python range() = Numpy arange()
---

In [11]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [13]:
np.arange(100,10,-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [14]:
arr3 = np.arange(0,10)

In [18]:
print(arr3.shape,arr3.size,arr3.ndim,arr3.dtype,arr3.itemsize,arr3.nbytes)

(10,) 10 1 int64 8 80


---

### 0 lar ile array oluşturma (np.zeros())
---

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

---

### 1 ler ile array oluşturma (np.ones())
---

In [20]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.repeat(10,5)

array([10, 10, 10, 10, 10])

In [22]:
np.full(5,10)

array([10, 10, 10, 10, 10])

---

### Numpy da filtreleme
---

In [21]:
ar1 = np.arange(1,20)
ar1[ar1%2==1] # ar1 içerisindeki verilerden tek sayı olanlar

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

---

### Random sayı oluşturma -1<1
---

In [30]:
np.random.random(4)

array([0.60662791, 0.06673124, 0.14527252, 0.3349332 ])

---

### random.randint
---

In [27]:
#0 dan 500 e kadar 5 farklı sayı üret
np.random.randint(0,500,5)

array([365,  18, 213,  39, 364])

---

### random.seed() kullanımı
---

In [32]:
#çekirdek değeri aynı sayıları tekrar üretmek için kullanılır
np.random.seed(123)
np.random.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [33]:
np.random.seed(101)
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [34]:
np.random.seed(101)
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

---

### ndenumerate 
* for döngülerinde değişkenlerin indexine de erişmek için kullanılır
***

In [22]:
arr1

array([10, 20, 30, 40, 50, 60])

In [24]:
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


---

### median()
* İçerisine gönderdiğiniz array'in medyanını bulmak için kullanılır


In [25]:
arr2 = np.arange(1,20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [27]:
np.median(arr2)

10.0

---

### cumsum()
* İçerisine gönderdiğiniz array'in kümülatif toplamını verir

In [28]:
np.cumsum(arr2)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190])

---

### amin()
* İçerisine gönderdiğiniz arrayin axis e göre sütun veya satırlarının minimum değerlerini döndürür

In [29]:
A = np.array([[1,2,3,0],[5,6,7,22],[10,11,1,3],[14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1,  3],
       [14, 15, 16,  3]])

In [33]:
#Sütunların en küçük değerleri
np.amin(A, axis=0)

array([1, 2, 1, 0])

In [32]:
#Satırların en küçük değerleri
np.amin(A, axis=1)

array([0, 5, 1, 3])

---

### std()
* İçerisine gönderdiğiniz array'in standart sapmasını döner

In [34]:
np.std(A)

6.324246496619182

---

### Array'in içerisine index ile ulaşma

In [35]:
a = np.array([7,5,3,9,0,2])
a[0]

7

In [36]:
a[1:4]

array([5, 3, 9])

In [37]:
a[-1]

2

---

### where kullanımı
* Bir koşula dayalı olarak bir arraydan yeni bir array yaratmak

In [38]:
ar = np.arange(1,20)

In [39]:
# ar arrayin içerisindeki çift sayıların yerine 0 yaz ve rep1 e at
rep1= np.where(ar%2==0, 0, ar)
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [40]:
ar2 = np.array([10,20,30,10,10,20,20])

In [41]:
# ar2 arrayinin içerisindeki 10 a eşit değerleri 99 ile değiştir ve bunu rep2 at
rep2 = np.where(ar2 == 10, 99, ar2)
print(rep2)

[99 20 30 99 99 20 20]


In [58]:
a1 = np.arange(0,60)
a1[np.where((a1>20)&(a1<35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

---

### put()
* Bir arrayin belirli indexlerini değiştirme

In [42]:
p2 = np.arange(0,100,10)

In [43]:
# p2 arrayinin 0.3.5 indexlerindeki değerleri sırası ile 22 34 56 değerleri ile değiştir
np.put(p2, [0,3,5],[22,34,56])
p2

array([22, 10, 20, 34, 40, 56, 60, 70, 80, 90])

---

### Eksik değerler ile ilgilenme (Missing Values)

In [44]:
a = np.array([10,np.nan,20,30,60,np.nan,90,np.inf])
a

array([10., nan, 20., 30., 60., nan, 90., inf])

In [47]:
np.isnan(a)

array([False,  True, False, False, False,  True, False, False])

In [48]:
# nan değerlerin hangi indexlerde olduğunu verir
np.where(np.isnan(a))

(array([1, 5]),)

In [49]:
# nan değerleri doldurma
a[np.isnan(a)]= 99
a

array([10., 99., 20., 30., 60., 99., 90., inf])

In [52]:
np.isnan(a).any()

False

---

### Dizileri birleştirme (yatay ve dikey)

In [53]:
a = np.zeros(20).reshape(2, -1)
b = np.repeat(1,20).reshape(2, -1)

In [54]:
# Vertical dikey olarak birleştirir
np.vstack([a,b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [55]:
# Horizontal yatay olarak birleştirir
np.hstack([a,b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

---

### intersect1d
* iki arrayin ortak değerleri, kesişim kümesi bir array olarak döndürür

In [56]:
c1 = np.array([10,20,30,40,50,60])
c2 = np.array([12,20,33,40,55,60])

np.intersect1d(c1,c2)

array([20, 40, 60])

---

### setdiff1d
* ilk arrayin diğer arrayden farklı olan değerlerini döndürür.

In [57]:
np.setdiff1d(c1,c2)

array([10, 30, 50])

---

### isin()
* Bulunurluk kontrolü yapar

In [60]:
a = np.arange(10,80,10)
a

array([10, 20, 30, 40, 50, 60, 70])

In [62]:
# 11 ve 20 değerleri a arrayinde var mı
np.isin(a, [11,20])

array([False,  True, False, False, False, False, False])

In [63]:
a[np.isin(a,20)]

array([20])

In [64]:
np.isin(a,33)

array([False, False, False, False, False, False, False])

In [65]:
b = np.array([10,20,30,40,10,10,70,80,70,90])
b

array([10, 20, 30, 40, 10, 10, 70, 80, 70, 90])

In [66]:
np.isin(b, [10,70])

array([ True, False, False, False,  True,  True,  True, False,  True,
       False])

In [67]:
np.where(np.isin(b,[10,70]))

(array([0, 4, 5, 6, 8]),)

---

### Diziyi ters çevirme

In [68]:
a4 = np.arange(10,30)
a4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [70]:
#1
a4[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [71]:
#2
np.flip(a4)

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

---

### sort()
* array sıralama

In [72]:
a=np.array([10,5,2,22,12,92,17,33])
a

array([10,  5,  2, 22, 12, 92, 17, 33])

In [73]:
np.sort(a)

array([ 2,  5, 10, 12, 17, 22, 33, 92])

In [74]:
a3 = np.array([[3,2,8,1],[70,50,10,67],[45,25,75,15]])
a3

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15]])

In [75]:
#Satır bazlı sıralama
np.sort(a3)

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [77]:
#Sütun bazlı sıralama
np.sort(a3, axis=0)

array([[ 3,  2,  8,  1],
       [45, 25, 10, 15],
       [70, 50, 75, 67]])

In [78]:
a

array([10,  5,  2, 22, 12, 92, 17, 33])

In [81]:
# büyükten küçüğe sıralamak için önce küçükten büyüğe sıralayıp ters çeviriyoruz
c = np.sort(a)
np.flip(c)

array([92, 33, 22, 17, 12, 10,  5,  2])

---

### random.shuffle()
* array'i karıştırmak

In [82]:
p = np.arange(0,50)
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [83]:
np.random.shuffle(p)
p

array([ 7, 30,  9, 47, 14,  1, 44, 18, 41, 25,  3, 28, 16, 23, 43,  4, 22,
        5,  8, 40,  6, 49, 45, 20, 39,  2, 32, 33, 19, 15, 17, 29, 11, 21,
       10, 35, 24, 42, 46, 36, 13,  0, 27, 38, 34, 37, 26, 48, 12, 31])

In [84]:
# p arrayindeki en büyük 10 değeri bulma
n = 10
p[np.argsort(p)[-n:]]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [85]:
# p değerindeki en küçük 10 değeri bulma
n=10
p[np.argsort(-p)[-n:]]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

---

### unique()
* Arraydeki benzersiz değerleri getirir