# Numpy

## Numpy & List Benzerlikleri ve Farkları

* Numpy ve List de elemanlara aynı şekilde pozisyon bazlı erişim mevcuttur.
* Numpy ve List de elemanlara aynı şekilde aralıkla erişebiliriz ( np[0:2] ).
* Numpy ve List üzerinde aynı döngü kullanabiliriz (for i in np:)

* Numpy dizilerinde aynı tip eleman bulunur. Listlerde ise farklı tip elemanlar da bulunur.
* Numpy da otomatik foksiyonları kullanabiliriz (mean(), std()) ancak list de kullanamayız.

* Numpy list e göre çok daha hızlıdır.(50 kat 100 kat)


In [1]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

## Why Numpy

In [2]:
# Python list speed 2.2 seconds
import time
def trad_version():
    t1 = time.time()
    X = range(10000000)
    Y = range(10000000)
    Z = []
    for i in range (len (X)):
        Z. append (X[i] + Y[i])
    return time.time() - t1
trad_version()

2.2102842330932617

In [3]:
# Numpy Speed 0.05 seconds
def numpy_version():
    t1 = time.time()
    X = np.arange(10000000)
    Y = np.arange(10000000)
    Z = X + Y
    return time.time() - t1
numpy_version()

0.09064912796020508

## list to array
---

In [4]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [5]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [6]:
type(arr1)

numpy.ndarray

---

### Arrayin içindeki verinin tipi (dtype)
---

In [7]:
arr1.dtype

dtype('int64')

---

### Tip değiştirme (astype())
---

In [8]:
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

---

### Python range() = Numpy arange()
---

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [11]:
np.arange(100,10,-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [12]:
arr3 = np.arange(0,10)

In [13]:
print(arr3.shape,arr3.size,arr3.ndim,arr3.dtype,arr3.itemsize,arr3.nbytes)

(10,) 10 1 int64 8 80


---

### 0 lar ile array oluşturma (np.zeros())
---

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

---

### 1 ler ile array oluşturma (np.ones())
---

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.repeat(10,5)

array([10, 10, 10, 10, 10])

In [17]:
np.full(5,10)

array([10, 10, 10, 10, 10])

---

### Numpy da filtreleme
---

In [18]:
ar1 = np.arange(1,20)
ar1[ar1%2==1] # ar1 içerisindeki verilerden tek sayı olanlar

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

---

### Random sayı oluşturma -1<1
---

In [19]:
np.random.random(4)

array([0.48962375, 0.67197298, 0.5333859 , 0.51322567])

---

### random.randint
---

In [20]:
#0 dan 500 e kadar 5 farklı sayı üret
np.random.randint(0,500,5)

array([ 86,  11, 137, 236,  91])

---

### random.seed() kullanımı
---

In [21]:
#çekirdek değeri aynı sayıları tekrar üretmek için kullanılır
np.random.seed(123)
np.random.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [22]:
np.random.seed(101)
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [23]:
np.random.seed(101)
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

---

### ndenumerate 
* for döngülerinde değişkenlerin indexine de erişmek için kullanılır
***

In [24]:
arr1

array([10, 20, 30, 40, 50, 60])

In [25]:
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


---

### median()
* İçerisine gönderdiğiniz array'in medyanını bulmak için kullanılır


In [26]:
arr2 = np.arange(1,20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [27]:
np.median(arr2)

10.0

---

### cumsum()
* İçerisine gönderdiğiniz array'in kümülatif toplamını verir

In [28]:
np.cumsum(arr2)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190])

---

### amin()
* İçerisine gönderdiğiniz arrayin axis e göre sütun veya satırlarının minimum değerlerini döndürür

In [29]:
A = np.array([[1,2,3,0],[5,6,7,22],[10,11,1,3],[14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1,  3],
       [14, 15, 16,  3]])

In [30]:
#Sütunların en küçük değerleri
np.amin(A, axis=0)

array([1, 2, 1, 0])

In [31]:
#Satırların en küçük değerleri
np.amin(A, axis=1)

array([0, 5, 1, 3])

---

### std()
* İçerisine gönderdiğiniz array'in standart sapmasını döner

In [32]:
np.std(A)

6.324246496619182

---

### Array'in içerisine index ile ulaşma

In [33]:
a = np.array([7,5,3,9,0,2])
a[0]

7

In [34]:
a[1:4]

array([5, 3, 9])

In [35]:
a[-1]

2

---

### where kullanımı
* Bir koşula dayalı olarak bir arraydan yeni bir array yaratmak

(np.where(a%2==0, 0, a)) Yapılan işlem: a arrayinin içerisindeki 1. değer 2 ye tam bölünüyor mu? : False 2. değer bölünür mü?: True o zaman yerine 0 yaz.

In [36]:
ar = np.arange(1,20)

In [37]:
# ar arrayin içerisindeki çift sayıların yerine 0 yaz ve rep1 e at
rep1= np.where(ar%2==0, 0, ar)
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [38]:
ar2 = np.array([10,20,30,10,10,20,20])

In [39]:
# ar2 arrayinin içerisindeki 10 a eşit değerleri 99 ile değiştir ve bunu rep2 at
rep2 = np.where(ar2 == 10, 99, ar2)
print(rep2)

[99 20 30 99 99 20 20]


In [40]:
a1 = np.arange(0,60)
a1[np.where((a1>20)&(a1<35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

---

### put()
* Bir arrayin belirli indexlerdeki değerleri değiştirme

In [41]:
p2 = np.arange(0,100,10)

In [42]:
# p2 arrayinin 0.3.5 indexlerindeki değerleri sırası ile 22 34 56 değerleri ile değiştir
np.put(p2, [0,3,5],[22,34,56])
p2

array([22, 10, 20, 34, 40, 56, 60, 70, 80, 90])

---

### Eksik değerler ile ilgilenme (Missing Values)

In [43]:
a = np.array([10,np.nan,20,30,60,np.nan,90,np.inf])
a

array([10., nan, 20., 30., 60., nan, 90., inf])

In [44]:
np.isnan(a)

array([False,  True, False, False, False,  True, False, False])

In [45]:
# nan değerlerin hangi indexlerde olduğunu verir
np.where(np.isnan(a))

(array([1, 5]),)

In [46]:
# nan değerleri doldurma
a[np.isnan(a)]= 99
a

array([10., 99., 20., 30., 60., 99., 90., inf])

In [47]:
np.isnan(a).any()

False

---

### Dizileri birleştirme (yatay ve dikey)

In [48]:
a = np.zeros(20).reshape(2, -1)
b = np.repeat(1,20).reshape(2, -1)

In [49]:
# Vertical dikey olarak birleştirir
np.vstack([a,b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [50]:
# Horizontal yatay olarak birleştirir
np.hstack([a,b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

---

### intersect1d
* iki arrayin ortak değerleri, kesişim kümesi bir array olarak döndürür

In [51]:
c1 = np.array([10,20,30,40,50,60])
c2 = np.array([12,20,33,40,55,60])

np.intersect1d(c1,c2)

array([20, 40, 60])

---

### setdiff1d
* ilk arrayin diğer arrayden farklı olan değerlerini döndürür.

In [52]:
np.setdiff1d(c1,c2)

array([10, 30, 50])

---

### isin()
* Bulunurluk kontrolü yapar

In [53]:
a = np.arange(10,80,10)
a

array([10, 20, 30, 40, 50, 60, 70])

In [54]:
# 11 ve 20 değerleri a arrayinde var mı
np.isin(a, [11,20])

array([False,  True, False, False, False, False, False])

In [55]:
a[np.isin(a,20)]

array([20])

In [56]:
np.isin(a,33)

array([False, False, False, False, False, False, False])

In [57]:
b = np.array([10,20,30,40,10,10,70,80,70,90])
b

array([10, 20, 30, 40, 10, 10, 70, 80, 70, 90])

In [58]:
np.isin(b, [10,70])

array([ True, False, False, False,  True,  True,  True, False,  True,
       False])

In [59]:
np.where(np.isin(b,[10,70]))

(array([0, 4, 5, 6, 8]),)

---

### Diziyi ters çevirme

In [60]:
a4 = np.arange(10,30)
a4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [61]:
#1
a4[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [62]:
#2
np.flip(a4)

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

---

### sort()
* array sıralama

In [63]:
a=np.array([10,5,2,22,12,92,17,33])
a

array([10,  5,  2, 22, 12, 92, 17, 33])

In [64]:
np.sort(a)

array([ 2,  5, 10, 12, 17, 22, 33, 92])

In [65]:
a3 = np.array([[3,2,8,1],[70,50,10,67],[45,25,75,15]])
a3

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15]])

In [66]:
#Satır bazlı sıralama
np.sort(a3)

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [67]:
#Sütun bazlı sıralama
np.sort(a3, axis=0)

array([[ 3,  2,  8,  1],
       [45, 25, 10, 15],
       [70, 50, 75, 67]])

In [68]:
a

array([10,  5,  2, 22, 12, 92, 17, 33])

In [69]:
# büyükten küçüğe sıralamak için önce küçükten büyüğe sıralayıp ters çeviriyoruz
c = np.sort(a)
np.flip(c)

array([92, 33, 22, 17, 12, 10,  5,  2])

---

### random.shuffle()
* array'i karıştırmak

In [70]:
p = np.arange(0,50)
p

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [71]:
np.random.shuffle(p)
p

array([45, 17, 11, 16, 26, 18, 39, 21,  1, 27, 33, 38, 13, 24,  2, 25, 47,
       14,  6, 22, 20, 35,  7,  3, 36, 49, 37, 15, 30, 32,  9, 46, 23, 31,
       44, 10, 41, 42, 34, 43,  8, 19, 48, 29, 12,  5,  0, 28, 40,  4])

In [72]:
# p arrayindeki en büyük 10 değeri bulma
n = 10
p[np.argsort(p)[-n:]]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [73]:
# p değerindeki en küçük 10 değeri bulma
n=10
p[np.argsort(-p)[-n:]]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

---

### unique()
* Arraydeki benzersiz değerleri getirir

In [74]:
b = np.array([10,10,10,20,30,30,20,10,20,30])
np.unique(b)

array([10, 20, 30])

---

### Hangi değerden kaç adet bulunuyor?

In [75]:
val, count = np.unique(b, return_counts=True)
val, count 
#10 değerinden 4 adet, 20 değerinden 3 adet, 30 değerinden 3 adet bulunmaktaymış.

(array([10, 20, 30]), array([4, 3, 3]))

---

### En fazla tekrar eden değer hangisi?

In [76]:
np.bincount(b).argmax()

10

---

### Arrayin değiştirilmesini engellemek sadece okunabilir kılmak.

In [77]:
d5 = np.arange(10, 100, 10)
d5

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [78]:
d5.flags.writeable = False
#yazılabilir olması durumunu kaldırdık ve artık üstüne yazılamaz.

In [79]:
#Göründüğü üzere değişiklik yapamıyoruz.
# d5[2]=11

---

### Dosya yükleme

In [80]:
p4 = np.loadtxt('Data/sample.txt', dtype=np.integer)
p4

array([[24, 29, 88],
       [ 1,  0,  8],
       [33,  7, 99],
       [39, 11, 98],
       [22, 76, 87]])

In [81]:
p5 = np.genfromtxt('Data/sample0.txt', dtype='str')
p5

array([['Dogu', 'Turkey', 'Football'],
       ['John', 'USA', 'Hockey'],
       ['Paul', 'Canada', 'Basketball']], dtype='<U10')

In [82]:
p5[0]

array(['Dogu', 'Turkey', 'Football'], dtype='<U10')

In [83]:
p5[:,0]

array(['Dogu', 'John', 'Paul'], dtype='<U10')

In [84]:
#Dosyanın belirli bölümünü yüklemek
np.loadtxt('Data/sample.txt', usecols=(0,2))
#0. ve 2. sütünları getirdi.

array([[24., 88.],
       [ 1.,  8.],
       [33., 99.],
       [39., 98.],
       [22., 87.]])

---

### Dosya kaydetme

In [85]:
p7 = np.arange(10,200,11)
p7

array([ 10,  21,  32,  43,  54,  65,  76,  87,  98, 109, 120, 131, 142,
       153, 164, 175, 186, 197])

In [86]:
np.savetxt('savingExample.csv',p7,delimiter=',')
#Değerlerin aralarını ',' ile ayırdık.

---

### Print seçenekleri (Print Options)

In [87]:
np.set_printoptions(precision=4)
#Virgülden sonra 4 basamak gösterilsin dedik (precision=4)
a=np.array([12.23445234,23.45645437])
a

array([12.2345, 23.4565])

In [88]:
np.set_printoptions(threshold=3)
#Arrayin ilk 3 ve son 3 değerini göstermesini istedik
np.arange(200)

array([  0,   1,   2, ..., 197, 198, 199])

In [89]:
#Resetlemek için formatter=None yapmamız lazım
np.set_printoptions(precision=8,suppress=False, threshold=1000,formatter=None)

In [90]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### Vektör toplama

In [91]:
#1
v1 = np.array([1,2])
v2 = np.array([3,4])
v3=v1+v2
v3

array([4, 6])

In [92]:
#2
v3 = np.add(v1,v2)
v3

array([4, 6])

---

### Vektör çarpma

In [93]:
a1 = np.array([5,6,8])
a2 = np.array([4,7,9])
print(np.multiply(a1,a2))

[20 42 72]


---

### Noktasal çarpım

In [94]:
#1
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
dotp= a1@a2
print('Dot product with@ - ',dotp)
#2
dotp = np.dot(a1,a2)
print('Dot product with np.dot - ',dotp)
#3
dotp = np.inner(a1,a2)
print('Dot product with np.inner - ',dotp)
#4
dotp = sum(np.multiply(a1,a2))
print('Dot product with sum&multiply - ',dotp)
#5
dotp = np.matmul(a1,a2)
print('Dot product with np.matmul - ',dotp)

Dot product with@ -  32
Dot product with np.dot -  32
Dot product with np.inner -  32
Dot product with sum&multiply -  32
Dot product with np.matmul -  32


---

### Vektörlerin uzunluğu
* ! Kendisiyle olan noktasal çarpımının karekökü (pisagor)

In [95]:
v3 = np.array([1,2,3,4,5,6])
length = np.sqrt(v3@v3)
length

9.539392014169456

---

### Normalizasyon
* Vektörün, uzunluğuna bölümü

In [101]:
#1
v1 = np.array([2,3])
length_v1 = np.sqrt(v1@v1)
norm_v1 = v1/length_v1
print('Vector length - ',length_v1)
print('Normalizated vector - ',norm_v1)

Vector length -  3.605551275463989
Normalizated vector -  [0.5547002  0.83205029]


In [102]:
#2
v1 = np.array([2,3])
norm_v1 = v1/np.linalg.norm(v1)
norm_v1

array([0.5547002 , 0.83205029])

---

## Matrisler

### Matris oluşturma

In [103]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [105]:
z1 = np.zeros((4,4))
z1.shape # Boyutu 4 e 4

(4, 4)

In [106]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [108]:
np.random.randint(0,500,(10,10)) #Matris oluşturmak için 1 parantez daha ekliyoruz

array([[253, 397, 431, 433, 280, 404, 448, 180, 316, 303],
       [370, 285, 316, 309, 395,  40, 219, 301,  97, 408],
       [292, 166, 137, 125,  52,  67, 299, 129,  79,  68],
       [196, 484,  61, 146, 307, 270, 412, 401,  87,  46],
       [ 52, 144, 454, 455,  84,  10, 190, 362,  96, 122],
       [235, 498, 487, 493, 185, 151, 470, 469,  26,  76],
       [ 66, 232,  54, 145, 193, 185, 473, 258,  80,  50],
       [322,  88,  79, 349,   6, 348,  42,  22, 377, 244],
       [368, 404, 409, 383,  97, 110, 438,  71, 456, 208],
       [221, 192, 364,  63, 488, 359, 208, 422, 301, 359]])

---

### vektör'ü matrise çevirme (reshape())

In [109]:
mat1 = np.random.randint(0,500,100).reshape(10,10)
mat1

array([[103, 372, 163,  25, 223,  75, 456,  11, 332, 207],
       [369, 379, 306, 239, 150, 101,  59, 322, 358, 490],
       [122,   1,  34,  37, 441,  35, 298, 115, 357, 172],
       [242, 108, 177, 159,  79,  85,   3, 311, 329, 221],
       [478,  99,  40, 182, 472, 350, 359, 470, 245, 145],
       [245, 247,  68, 401, 402, 444, 339,  82, 135,  67],
       [252, 418, 251,  76, 383,  94, 119, 276, 453, 329],
       [ 59,  34, 453, 123, 376,  25, 206, 476, 330,  75],
       [289, 393, 427,  20, 210, 158, 259, 430, 285,  47],
       [496,  27, 465, 455,  25, 238,  94, 102, 185, 405]])

---

### Matrislerde değerlere erişme

In [110]:
mat1[0,0] #0.satır 0.sütun

103

---

### Matrislerde kısıtlama

In [111]:
mat1[mat1>400] #Matris içerisindeki 400 den büyük değerler

array([456, 490, 441, 478, 472, 470, 401, 402, 444, 418, 453, 453, 476,
       427, 430, 496, 465, 455, 405])

---

### Birim matris

In [112]:
I=np.eye(9)
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

---

### Diagonal matris

In [113]:
D=np.diag([1,2,3,4,5,6,7,8])
D

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

---

### Üçgen matris

In [117]:
M = np.random.rand(5,5)
U = np.triu(M) #Üst üçgen
L = np.triu(M) #Alt üçgen

print(M)
print('------------------------------------------')
print(U)
print('------------------------------------------')
print(L)

[[0.57784515 0.85315298 0.17328627 0.32027289 0.03878806]
 [0.94670795 0.15074552 0.22616058 0.8897609  0.99916662]
 [0.01767706 0.00120884 0.08842728 0.36417028 0.66855505]
 [0.41465704 0.32508369 0.94845624 0.36060823 0.52834171]
 [0.33842466 0.84198489 0.37360641 0.90071777 0.5893177 ]]
------------------------------------------
[[0.57784515 0.85315298 0.17328627 0.32027289 0.03878806]
 [0.         0.15074552 0.22616058 0.8897609  0.99916662]
 [0.         0.         0.08842728 0.36417028 0.66855505]
 [0.         0.         0.         0.36060823 0.52834171]
 [0.         0.         0.         0.         0.5893177 ]]
------------------------------------------
[[0.57784515 0.85315298 0.17328627 0.32027289 0.03878806]
 [0.         0.15074552 0.22616058 0.8897609  0.99916662]
 [0.         0.         0.08842728 0.36417028 0.66855505]
 [0.         0.         0.         0.36060823 0.52834171]
 [0.         0.         0.         0.         0.5893177 ]]


---

### Matrisi vektöre çevirmek

In [118]:
A = np.arange(1,17).reshape(4,4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [120]:
#1
A.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [123]:
#2
A.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

---

### Satır-Sütun yer değiştirme

In [124]:
m1 = np.arange(0,16).reshape(4,4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [125]:
m1[[3,2]] = m1[[2,3]]
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11]])

In [126]:
m2 = np.arange(0,36).reshape(6,6)
m2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [127]:
m2[:,[0,1]] = m2[:,[1,0]]
m2

array([[ 1,  0,  2,  3,  4,  5],
       [ 7,  6,  8,  9, 10, 11],
       [13, 12, 14, 15, 16, 17],
       [19, 18, 20, 21, 22, 23],
       [25, 24, 26, 27, 28, 29],
       [31, 30, 32, 33, 34, 35]])

---

### Matris birleştirme (concatenate)

In [128]:
A=np.array([[1,2],[3,4],[5,6]])
B=np.array([[1,1],[1,1]])
C=np.concatenate((A,B))
C

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 1],
       [1, 1]])

---

### Matris Toplama

In [130]:
M=np.array([[1,2,3],[4,-3,6],[7,8,0]])
N=np.array([[1,1,1],[2,2,2],[3,3,3]])
C=M+N
print('\n Matrix Addition (M+N)==> \n',C)
#2
C=np.add(M,N,dtype=np.float64)
print('\n Matrix Addition using np.add ==> \n',C)


 Matrix Addition (M+N)==> 
 [[ 2  3  4]
 [ 6 -1  8]
 [10 11  3]]

 Matrix Addition using np.add ==> 
 [[ 2.  3.  4.]
 [ 6. -1.  8.]
 [10. 11.  3.]]


---

### Matris Cikartma

In [132]:
#1
C=M-N
print('\n Matrix Substract (M-N)==> \n',C)
#2
C= np.subtract(M,N,dtype=np.float64)
print('\n Matrix Subtract using np.substract ==> \n', C)


 Matrix Substract (M-N)==> 
 [[ 0  1  2]
 [ 2 -5  4]
 [ 4  5 -3]]

 Matrix Subtract using np.substract ==> 
 [[ 0.  1.  2.]
 [ 2. -5.  4.]
 [ 4.  5. -3.]]


---

### Matris Carpma

In [133]:
#1
C=M*N
print('\n Matrix Multiply (M*N) ==> \n',C)
#2
C=np.multiply(M,N,dtype=np.float64)
print('\n Matrix Multiply using np.multiply ==> \n', C)


 Matrix Multiply (M*N) ==> 
 [[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]

 Matrix Multiply using np.multiply ==> 
 [[ 1.  2.  3.]
 [ 8. -6. 12.]
 [21. 24.  0.]]


---

### Matris Bolme

In [136]:
#1
C=M/N
print('\n Matrix Divide (M/N) ==> \n', C)
#2
C= np.divide(M,N,dtype=np.float64)
print('\n Matrix Divide using np.divide ==> \n', C)


 Matrix Divide (M/N) ==> 
 [[1.         2.         3.        ]
 [2.         2.5        3.        ]
 [2.33333333 2.66666667 0.        ]]

 Matrix Divide using np.divide ==> 
 [[1.         2.         3.        ]
 [2.         2.5        3.        ]
 [2.33333333 2.66666667 0.        ]]


---

### Transpose

In [137]:
#1
M=np.array([[1,2,3],[4,5,6],[7,8,0]])
print('Transpose of M ==> \n', np.transpose(M))
#2
print('Transpose of M ==> \n', M.T)

Transpose of M ==> 
 [[1 4 7]
 [2 5 8]
 [3 6 0]]
Transpose of M ==> 
 [[1 4 7]
 [2 5 8]
 [3 6 0]]


---

### Determinant

In [138]:
M=np.array([[1,2,3],[4,-3,6],[7,8,9]])
print('Determinant of M ==>', np.linalg.det(M))

Determinant of M ==> 95.99999999999999


---

### Ters Alma

In [139]:
print('Inverse of M ==> \n', np.linalg.inv(M))

Inverse of M ==> 
 [[-0.78125     0.0625      0.21875   ]
 [ 0.0625     -0.125       0.0625    ]
 [ 0.55208333  0.0625     -0.11458333]]


---

### Kuvvet Alma

In [140]:
m1 = np.array([[1,2],[4,5]])
m1

array([[1, 2],
       [4, 5]])

In [144]:
#1
print('Kuvvet alma using @ ==> \n',m1@m1@m1)
#2
print('Kuvvet alma using linalg.matrix_power ==> \n', np.linalg.matrix_power(m1,3))

Kuvvet alma using @ ==> 
 [[ 57  78]
 [156 213]]
Kuvvet alma using linalg.matrix_power ==> 
 [[ 57  78]
 [156 213]]


---

# Tensorler

### Tensor olusturma

In [145]:
T1= np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,20,30],[40,50,60],[70,80,90]],
    [[100,200,300],[400,500,600],[700,800,900]]
])
T1

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [146]:
T2 = np.array([
    [[0,0,0],[0,0,0],[0,0,0]],
    [[1,1,1],[1,1,1],[1,1,1]],
    [[2,2,2],[2,2,2],[2,2,2]]
])
T2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

---

### Tensor Toplama

In [147]:
#1
A=T1+T2
A

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [148]:
#2
A=np.add(T1,T2)
A

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

---

### Tensor Bolme

In [151]:
#1
D=T1/T2
D

array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

In [152]:
#2
D=np.divide(T1,T2)
D

array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

---

### Tensorlerde Noktasal Carpim

In [153]:
np.tensordot(T1,T2)

array([[  63,   63,   63],
       [ 630,  630,  630],
       [6300, 6300, 6300]])